# Generated by Django 3.1.7 on 2021-03-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDB',
            fields=[
                ('user', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('className', models.CharField(blank=True, max_length=200)),
                ('chatno', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
