# Generated by Django 3.1.7 on 2021-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinktype', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('uplimit', models.IntegerField(null=True)),
                ('downlimit', models.IntegerField(null=True)),
                ('totalorder', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='foodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('foodtype', models.CharField(choices=[('1', 'Veg'), ('2', 'Non-Veg')], max_length=10)),
            ],
        ),
    ]
