# Generated by Django 3.1.7 on 2021-03-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_barmenu_foodmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barmenu',
            options={'verbose_name_plural': 'Bar Menu'},
        ),
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'verbose_name_plural': 'Food Menu'},
        ),
    ]
