# Generated by Django 3.1.7 on 2021-03-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210327_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='className',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
