# Generated by Django 3.1.7 on 2021-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
