# Generated by Django 3.1.7 on 2021-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_foodmenu_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='mostBid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='newest',
            field=models.BooleanField(default=False),
        ),
    ]
