# Generated by Django 3.1.7 on 2021-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210328_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='mostBid',
        ),
        migrations.AddField(
            model_name='barmenu',
            name='mostBid',
            field=models.BooleanField(default=False),
        ),
    ]
