# Generated by Django 3.1.7 on 2021-03-27 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210328_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='ratings',
            field=models.IntegerField(default=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
