# Generated by Django 3.1.7 on 2021-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_foodmenu_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barmenu',
            name='downlimit',
        ),
        migrations.RemoveField(
            model_name='barmenu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='barmenu',
            name='totalorder',
        ),
        migrations.RemoveField(
            model_name='barmenu',
            name='uplimit',
        ),
        migrations.AddField(
            model_name='barmenu',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='barmenu',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
