# Generated by Django 3.1.7 on 2021-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210329_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barmenu',
            old_name='mostBid',
            new_name='recommended_drink',
        ),
        migrations.AddField(
            model_name='barmenu',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='barmenu',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='barmenu',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='barmenu',
            name='savings',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='barmenu',
            name='tot_qty',
            field=models.IntegerField(null=True),
        ),
    ]
