# Generated by Django 3.1.7 on 2021-03-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210329_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmenu',
            name='className',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
