# Generated by Django 3.1.7 on 2021-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_barmenu_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('1', 'Soup'), ('2', 'Salad'), ('3', 'Appetizers'), ('4', 'Italian Mainfare'), ('5', 'Mexican Mainfare'), ('6', 'Sizzlers'), ('7', 'Fondue'), ('8', 'Pastas'), ('9', 'Pizzas'), ('10', 'Desserts')], max_length=10),
        ),
    ]
