# Generated by Django 3.1.7 on 2021-03-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210330_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ordered',
            },
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('1', 'Rice'), ('2', 'Salad'), ('3', 'Appetizers'), ('4', 'Italian Mainfare'), ('5', 'Mexican Mainfare'), ('6', 'Soup'), ('7', 'Fondue'), ('8', 'Pastas'), ('9', 'Pizzas'), ('10', 'Desserts')], max_length=10),
        ),
    ]
