# Generated by Django 3.1.7 on 2021-03-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210330_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barmenu',
            name='drinktype',
            field=models.CharField(blank=True, choices=[('1', 'Beer'), ('2', 'Cocktail'), ('3', 'Gin'), ('4', 'Red Wine'), ('5', 'Sparkling Wine'), ('6', 'Vodka'), ('7', 'Whiskey'), ('8', 'White Wine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('1', 'Rice'), ('2', 'Salad'), ('3', 'Appetizers'), ('4', 'Italian Mainfare'), ('5', 'Mexican Mainfare'), ('6', 'Soup'), ('7', 'Fondue'), ('8', 'Pastas'), ('9', 'Pizzas'), ('10', 'Desserts')], max_length=50),
        ),
    ]
