# Generated by Django 3.1.7 on 2021-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210330_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='status',
        ),
        migrations.AddField(
            model_name='ordered',
            name='cooked',
            field=models.BooleanField(default=False),
        ),
    ]
