# Generated by Django 3.1.7 on 2021-03-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210330_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordered',
            old_name='name',
            new_name='dish_name',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='confirmed',
        ),
    ]
