# Generated by Django 3.1.7 on 2021-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210331_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
